version: "3"
services:
  blips-app:
    build:
      context: ../.
      dockerfile: docker/Dockerfile.devcontainer

    volumes:
      - ..:/blips-app:cached
      - extensions-cache:/home/vscode/.vscode-server

    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  extensions-cache:
